// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindsorX_2027.DB_Entity;

#nullable disable

namespace BaggrundsDataLibrary.Migrations
{
    [DbContext(typeof(Entity_Database))]
    [Migration("20241129074357_ind")]
    partial class ind
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaggrundsDataLibrary.LagerTransAktioner.TransaktionerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrugerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdreNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProduktAntal")
                        .HasColumnType("float");

                    b.Property<string>("ProduktNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProduktNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransaktionsDato")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransaktionsType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transaktioner");
                });

            modelBuilder.Entity("WindsorX_2027.IndkoebsModel.IndkobModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("kundeNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leverandorNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("open")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ordreDato")
                        .HasColumnType("datetime2");

                    b.Property<string>("ordreDetaljer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ordreNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referenceDetaljer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IndkobsOrdre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            kundeNummer = "1",
                            leverandorNummer = "1",
                            open = true,
                            ordreDato = new DateTime(2024, 11, 29, 8, 43, 56, 942, DateTimeKind.Local).AddTicks(9369),
                            ordreNummer = "1"
                        },
                        new
                        {
                            Id = 2,
                            kundeNummer = "1",
                            leverandorNummer = "1",
                            open = true,
                            ordreDato = new DateTime(2024, 11, 29, 8, 43, 56, 942, DateTimeKind.Local).AddTicks(9456),
                            ordreNummer = "1"
                        },
                        new
                        {
                            Id = 3,
                            kundeNummer = "1",
                            leverandorNummer = "1",
                            open = true,
                            ordreDato = new DateTime(2024, 11, 29, 8, 43, 56, 942, DateTimeKind.Local).AddTicks(9459),
                            ordreNummer = "2"
                        },
                        new
                        {
                            Id = 4,
                            kundeNummer = "1",
                            leverandorNummer = "1",
                            open = true,
                            ordreDato = new DateTime(2024, 11, 29, 8, 43, 56, 942, DateTimeKind.Local).AddTicks(9461),
                            ordreNummer = "2"
                        });
                });

            modelBuilder.Entity("WindsorX_2027.IndkoebsModel.LeverandorReg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firmanavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("byNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kontaktOplysninger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kontaktPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leverandorNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefonNummer1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefonNummer2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leverandorer");
                });

            modelBuilder.Entity("WindsorX_2027.IndkoebsModel.OrdreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IndkobModelId")
                        .HasColumnType("int");

                    b.Property<string>("enheder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("kostPris")
                        .HasColumnType("float");

                    b.Property<string>("leverandørNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ordreAntal")
                        .HasColumnType("float");

                    b.Property<string>("vareNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vareTekst")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndkobModelId");

                    b.ToTable("OrdreLinjer");
                });

            modelBuilder.Entity("WindsorX_2027.LagerModel.Lagermodel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("bestiltAntal")
                        .HasColumnType("float");

                    b.Property<string>("enheder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("kostPris")
                        .HasColumnType("float");

                    b.Property<DateTime?>("lagerOptaltDato")
                        .HasColumnType("datetime2");

                    b.Property<string>("location1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("maxLager")
                        .HasColumnType("float");

                    b.Property<double?>("minLager")
                        .HasColumnType("float");

                    b.Property<DateTime?>("oprDato")
                        .HasColumnType("datetime2");

                    b.Property<double?>("salgsPris")
                        .HasColumnType("float");

                    b.Property<DateTime?>("sidsteBestillingsDato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("sidsteLagerBevDato")
                        .HasColumnType("datetime2");

                    b.Property<double?>("vareMaengde")
                        .HasColumnType("float");

                    b.Property<string>("vareNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vareTekst")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LagerData");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            bestiltAntal = 0.0,
                            enheder = "stk",
                            kostPris = 2500.0,
                            maxLager = 1.0,
                            minLager = 0.0,
                            vareMaengde = 1.0,
                            vareNummer = "2",
                            vareTekst = "Motor"
                        },
                        new
                        {
                            Id = 4,
                            bestiltAntal = 0.0,
                            enheder = "mtr",
                            kostPris = 150.0,
                            maxLager = 5.0,
                            minLager = 1.0,
                            vareMaengde = 5.0,
                            vareNummer = "4",
                            vareTekst = "gevind"
                        });
                });

            modelBuilder.Entity("WindsorX_2027.IndkoebsModel.OrdreModel", b =>
                {
                    b.HasOne("WindsorX_2027.IndkoebsModel.IndkobModel", "IndkobModel")
                        .WithMany("ordreLinjer")
                        .HasForeignKey("IndkobModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndkobModel");
                });

            modelBuilder.Entity("WindsorX_2027.IndkoebsModel.IndkobModel", b =>
                {
                    b.Navigation("ordreLinjer");
                });
#pragma warning restore 612, 618
        }
    }
}
