// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindsorX_2027.DB_Entity;

#nullable disable

namespace WindsorX_2027.Migrations
{
    [DbContext(typeof(Entity_Database))]
    partial class Entity_DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WindsorX_2027.LagerModel.Lagermodel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("bestiltAntal")
                        .HasColumnType("float");

                    b.Property<string>("enheder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("kostPris")
                        .HasColumnType("float");

                    b.Property<DateTime?>("lagerOptaltDato")
                        .HasColumnType("datetime2");

                    b.Property<string>("location1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("maxLager")
                        .HasColumnType("float");

                    b.Property<double?>("minLager")
                        .HasColumnType("float");

                    b.Property<DateTime?>("oprDato")
                        .HasColumnType("datetime2");

                    b.Property<double?>("salgsPris")
                        .HasColumnType("float");

                    b.Property<DateTime?>("sidsteBesstillingsDato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("sidsteLagerBevDato")
                        .HasColumnType("datetime2");

                    b.Property<double?>("vareMaengde")
                        .HasColumnType("float");

                    b.Property<string>("vareNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vareTekst")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LagerData");
                });
#pragma warning restore 612, 618
        }
    }
}
